name: IP地址国家归属检查

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-ip-country:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install ip2region
          
      - name: 创建IP处理脚本
        run: |
          cat > process_ips.py << 'EOF'
          import sys
          from ip2region import Ip2Region
          
          def get_country_code(ip):
              try:
                  # 初始化ip2region数据库
                  db = Ip2Region()
                  data = db.memory_search(ip)
                  # 解析返回结果
                  # 结果格式: [城市id, 国家, 地区, 省份, 城市, ISP]
                  if data and len(data) > 1:
                      country = data[1]
                      # 映射常见国家到标准代码
                      country_map = {
                          '中国': 'CN',
                          '美国': 'US',
                          '日本': 'JP',
                          '韩国': 'KR',
                          '英国': 'GB',
                          '法国': 'FR',
                          '德国': 'DE',
                          '澳大利亚': 'AU',
                          '加拿大': 'CA'
                          # 可以根据需要添加更多国家映射
                      }
                      return country_map.get(country, 'UNKNOWN')
                  else:
                      return 'UNKNOWN'
              except Exception as e:
                  print(f"查询IP {ip} 时出错: {str(e)}")
                  return 'UNKNOWN'
          
          # 读取IP文件并处理
          with open('ip_with_country.txt', 'w', encoding='utf-8') as out_file:
              with open('ip.txt', 'r', encoding='utf-8') as in_file:
                  for line in in_file:
                      line = line.strip()
                      # 跳过空行和已包含国家标签的行
                      if not line or '#' in line:
                          out_file.write(line + '\n')
                          continue
                      
                      # 处理IP地址
                      parts = line.split()
                      if not parts:
                          out_file.write(line + '\n')
                          continue
                      
                      ip = parts[0]
                      country_code = get_country_code(ip)
                      # 保留IP后面的其他信息
                      rest_info = ' '.join(parts[1:])
                      if rest_info:
                          out_file.write(f"{ip} {rest_info} #{country_code}\n")
                      else:
                          out_file.write(f"{ip} #{country_code}\n")
                      print(f"处理IP: {ip} -> 国家代码: {country_code}")
          EOF
      
      - name: 检查IP地址归属国家
        run: |
          # 创建临时文件存储结果
          touch ip_with_country.txt
          
          # 下载最新的IP清单
          if [ -f "ip.txt" ]; then
            echo "正在处理本地ip.txt文件..."
            IP_FILE="ip.txt"
          else
            echo "正在下载远程IP清单..."
            curl -o ip.txt "https://raw.githubusercontent.com/tianshipapa/cfipcaiji/refs/heads/main/ip.txt"
            IP_FILE="ip.txt"
          fi
          
          # 使用Python脚本处理IP地址
          python3 process_ips.py
          
          # 用新文件替换旧文件
          mv ip_with_country.txt ip.txt
          
      - name: 提交更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '自动更新IP地址国家归属标签'
          branch: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
